# -*- coding: utf-8 -*-
"""OSS Project 2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IjmXcNQtBbZLX-toPtk6HtzuLSIQOAiN
"""

import pandas as pd
data = pd.read_csv("2019_kbo_for_kaggle_v2.csv")
data2=data[data['p_year']<=2018]
data3=data[data['p_year']>=2015]
kin=['H','avg','HR','OBP']
for i in range(0,4):
  print(data3.sort_values(by=kin[i], ascending=False).head(10))
print()
print()
poss = ["포수", "1루수", "2루수", "3루수", "유격수", "좌익수", "중견수", "우익수"]
data4=data[data['p_year']==2018]
for i in range(1,len(poss)):
  print(data4[data4.tp==poss[i]].sort_values(by='cp', ascending=False).head(1))

print()
print()
coln = ['R','H','HR','RBI','SB','war','avg','OBP','SLG']
maxcorr=0
maxcoln='ERR'
for i in coln:
  if data[i].corr(data['salary']) > maxcorr :
    maxcorr = data[i].corr(data['salary'])
    maxcoln=i
print(maxcoln,": ",maxcorr)







